### ISSUE TITLE
Exception while updating tag

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#153]
Stacktrace:
2016-06-13 16:31:01.7845 [] ERROR Exception ..., URL POST '/Tag/Edit/493', referrer 'http://vocadb.net/Tag/Edit/493' - System.ArgumentNullException Value cannot be null.
Parameter name: contract Void NotNull[T](System.Func`1[T])    at VocaDb.Model.ParamIs.NotNull[T](Func`1 arg) in C:\Sites\VocaDB\web-git\VocaDbModel\ParamIs.cs:line 116
   at VocaDb.Model.Domain.Globalization.EnglishTranslatedString.CopyFrom(EnglishTranslatedStringContract contract) in C:\Sites\VocaDB\web-git\VocaDbModel\Domain\Globalization\EnglishTranslatedString.cs:line 51
   at VocaDb.Model.Database.Queries.TagQueries.<>c__DisplayClass39_0.<Update>b__1(IDatabaseContext`1 ctx) in C:\Sites\VocaDB\web-git\VocaDbModel\Database\Queries\TagQueries.cs:line 668
   at VocaDb.Model.Database.Repositories.NHibernate.NHibernateRepository`1.HandleTransaction[TResult](Func`2 func, String failMsg) in C:\Sites\VocaDB\web-git\VocaDbModel\Database\Repositories\NHibernate\NHibernateRepository.cs:line 109
   at VocaDb.Web.Controllers.TagController.Edit(TagEditViewModel model) in C:\Sites\VocaDB\web-git\VocaDbWeb\Controllers\TagController.cs:line 152
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by riipah** [comment]
It's the description field. I don't know how it's possible to make it null though.
