### ISSUE TITLE
Tag tests are failing

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1874]
### Website (required)
All

### Describe the bug (required)
Some tag-related unit tests seem to be failing. It seems to be a logic change, and the test was probably not updated?

```
  Failed GetTagSuggestions [1 s]
  Error Message:
   Expected result.Length to be 2 because Number of tag suggestions, but found 0 (difference of -2).
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at VocaDb.Tests.Web.Controllers.DataAccess.AlbumQueriesTests.GetTagSuggestions() in C:\projects\vocadb\Tests\Web\Controllers\DataAccess\AlbumQueriesTests.cs:line 287
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
  Skipped GetHtml_HtmlAttribute
  Skipped IsValidFor_WithParam
  Failed SkipInvalidTarget [479 ms]
  Error Message:
   Expected entryTags.Length to be 1 because Number of tags, but found 2.
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at VocaDb.Tests.Service.Queries.TagUsageQueriesTests.SkipInvalidTarget() in C:\projects\vocadb\Tests\Service\Queries\TagUsageQueriesTests.cs:line 275
```

### Expected behavior (optional)
All tests pass

**Comment by FinnRG** [comment]
Will be fixed in branch langversion as described here: https://github.com/VocaDB/vocadb/pull/1873#issuecomment-2565468964

**Comment by riipah** [comment]
Okay, thank you. I was also going to take a look later, but if you have time to fix, even better.
