### ISSUE TITLE
SQL query error while getting artist's latest songs

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#252]
Seems like a bug in the latest NHibernate (4.1.0). Invalid SQL being generated.

```
2017-01-02 11:12:14.9604 [] ERROR Unexpected database error - NHibernate.Exceptions.GenericADOException could not execute query
[ select artistfors0_.[Song] as col_0_0_ from dbo.ArtistsForSongs artistfors0_ inner join dbo.Songs song1_ on artistfors0_.[Song]=song1_.Id where  not (song1_.[Deleted]=1) and artistfors0_.[Artist]=@p0 and  not (artistfors0_.[IsSupport]=1) and (song1_.[SongType]<>@p1 or artistfors0_.[Roles] & artistfors0_.[Roles]@p2<>@p3) and artistfors0_.[Roles]<>@p4 order by song1_.PublishDate desc, song1_.[CreateDate] desc OFFSET 0 ROWS FETCH FIRST @p5 ROWS ONLY ]
  Name:p1 - Value:470  Name:p2 - Value:64  Name:p3 - Value:1  Name:p4 - Value:0  Name:p5 - Value:32768  Name:p6 - Value:8
[SQL: select artistfors0_.[Song] as col_0_0_ from dbo.ArtistsForSongs artistfors0_ inner join dbo.Songs song1_ on artistfors0_.[Song]=song1_.Id where  not (song1_.[Deleted]=1) and artistfors0_.[Artist]=@p0 and  not (artistfors0_.[IsSupport]=1) and (song1_.[SongType]<>@p1 or artistfors0_.[Roles] & artistfors0_.[Roles]@p2<>@p3) and artistfors0_.[Roles]<>@p4 order by song1_.PublishDate desc, song1_.[CreateDate] desc OFFSET 0 ROWS FETCH FIRST @p5 ROWS ONLY] System.Collections.IList DoList(NHibernate.Engine.ISessionImplementor, NHibernate.Engine.QueryParameters, NHibernate.Transform.IResultTransformer)    at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at VocaDb.Model.Domain.Caching.ObjectCacheExtender.GetOrInsert[T](ObjectCache cache, String key, CacheItemPolicy cacheItemPolicy, Func`1 func) in C:\Sites\VocaDB\web-git\VocaDbModel\Domain\Caching\ObjectCacheExtender.cs:line 14
   at VocaDb.Model.Service.Queries.ArtistRelationsQuery.GetLatestSongIds(IDatabaseContext ctx, Artist artist) in C:\Sites\VocaDB\web-git\VocaDbModel\Service\Queries\ArtistRelationsQuery.cs:line 78
   at VocaDb.Model.Service.Queries.ArtistRelationsQuery.GetLatestSongs(IDatabaseContext ctx, Artist artist) in C:\Sites\VocaDB\web-git\VocaDbModel\Service\Queries\ArtistRelationsQuery.cs:line 94
   at VocaDb.Model.Service.Queries.ArtistRelationsQuery.GetRelations(Artist artist, ArtistRelationsFields fields) in C:\Sites\VocaDB\web-git\VocaDbModel\Service\Queries\ArtistRelationsQuery.cs:line 156
   at VocaDb.Model.Database.Queries.ArtistQueries.<>c__DisplayClass22_0.<GetDetails>b__0(IDatabaseContext`1 session) in C:\Sites\VocaDB\web-git\VocaDbModel\Database\Queries\ArtistQueries.cs:line 344
   at VocaDb.Model.Database.Repositories.NHibernate.NHibernateRepository`1.HandleQuery[TResult](Func`2 func, String failMsg) in C:\Sites\VocaDB\web-git\VocaDbModel\Database\Repositories\NHibernate\NHibernateRepository.cs:line 92
SqlException Incorrect syntax near '@p2'.
Invalid usage of the option FIRST in the FETCH statement. Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])
```

```artistfors0_.[Roles]@p2``` doesn't look like proper SQL. That ```@p2``` shouldn't be there. Maybe it's a caching problem in NH? I was unable to reproduce this while testing. Need to investigate more and maybe submit a bug report for NHibernate.

Reverted back to 4.0.3 until the issue is resolved.

**Comment by riipah** [comment]
Downgraded back to NH 4.0.3 for now

**Comment by riipah** [comment]
Reported https://nhibernate.jira.com/browse/NH-3928
