### ISSUE TITLE
Wiki VocaDB connector needs update

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#491]
Seems to be good old WCF serialization fault due to outdated contracts.

Stack trace:
```
Invalid enum value 'Bilibili' cannot be deserialized into type 'VocaDb.RoadkillAuth.VocaDbService.PVService'. Ensure that the necessary enum values are present and are marked with EnumMemberAttribute attribute if the type has DataContractAttribute attribute.
   at System.Runtime.Serialization.EnumDataContract.ReadEnumValue(String value, Int32 index, Int32 count)
   at System.Runtime.Serialization.EnumDataContract.ReadEnumValue(XmlReaderDelegator reader)
   at System.Runtime.Serialization.EnumDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadUserContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)

```

**Comment by AgFlore** [comment]
The issue occurred again. I cannot access the Wiki as long as I'm logged in. Not sure whether this is connected to the streaming service, as the wiki doesn't load even if I changed my preferred streaming service and cleared up VocaDB's cookies.

**Comment by riipah** [comment]
Yeah, this might happen any time changes are made on the VocaDB website, unfortunately. Please add a new ticket, because it's a new issue (even though the reason is the same).
