### ISSUE TITLE
Wiki VocaDB connector needs update

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#589]
The issue #491 occurred again. Cannot access the Wiki as long as I'm logged in. Not sure whether this is connected to the streaming service (as is the case in #491 ) as the wiki doesn't load even if I changed my preferred streaming service and cleared up VocaDB's cookies.

**Comment by riipah** [comment]
Logs

```
Exception information: 
    Exception type: FaultException`1 
    Exception message: An exception was thrown while activating VocaDb.Web.Services.QueryService -> VocaDb.Model.Database.Queries.ArtistQueries -> VocaDb.Model.Domain.Images.ServerEntryImageFactoryAggregator -> VocaDb.Web.Code.DynamicImageUrlFactory.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at VocaDb.RoadkillAuth.VocaDbService.QueryService.GetUserInfo(String name)
   at VocaDb.RoadkillAuth.VocaDbUserManager.GetContractOrDefault(String username)
```

DynamicImageUrlFactory cannot be activated because it relies on UrlHelper, which is not available in WCF. Need to add some fallback.

**Comment by riipah** [comment]
Ok, I just made it lazy, and AutoFac seems to handle it as expected. The wiki is working again for me at least.

**Comment by AgFlore** [comment]
Mine is working well now too.
