### ISSUE TITLE
Sometimes unable to add SoundCloud media

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#590]
Happens randomly.

Error from logs

```
2020-04-22 01:09:42.6226 [] ERROR Exception raised by web API - System.Net.Http.HttpRequestException An error occurred while sending the request. Void Throw()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VocaDb.Model.Helpers.HtmlRequestHelper.<GetStreamAsync>d__2`1.MoveNext() in C:\Sites\VocaDB\web\VocaDbModel\Helpers\HtmlRequestHelper.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VocaDb.Model.Helpers.JsonRequest.<ReadObjectAsync>d__1`1.MoveNext() in C:\Sites\VocaDB\web\VocaDbModel\Helpers\JsonRequest.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VocaDb.Model.Service.VideoServices.VideoServiceSoundCloud.<ParseBySoundCloudUrl>d__5.MoveNext() in C:\Sites\VocaDB\web\VocaDbModel\Service\VideoServices\VideoServiceSoundCloud.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VocaDb.Web.Controllers.Api.PVApiController.<GetPVByUrl>d__5.MoveNext() in C:\Sites\VocaDB\web\VocaDbWeb\Controllers\Api\PVApiController.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
WebException The request was aborted: Could not create SSL/TLS secure channel. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
```

"WebException The request was aborted: Could not create SSL/TLS secure channel." refers to an invalid certificate, or problem with SSL/TLS versions, same as what we had [with Twitter](https://www.thesslstore.com/blog/twitter-will-deprecate-support-for-tls-1-0-tls-1-1-on-july-15/) before.

But why is it working sometimes? Is it possible the Twitter fix is affecting SoundCloud?

**Comment by riipah** [comment]
It seems that forcing TLS below 1.2 causes this error. But why is it working by default for me even without setting it, I don't know.

**Comment by riipah** [comment]
Setting TLS 1.2 / TLS 1.3 when accessing SoundCloud API, same as Twitter. Let's see if it still happens.
