### ISSUE TITLE
Tag page timing out

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#591]
Happens when browsing to "rock" tag.

```
2020-04-24 09:32:14.9927 [] ERROR Unexpected database error - NHibernate.Exceptions.GenericADOException could not execute query
[ select song0_.Id as id1_63_, song0_.[CreateDate] as column2_63_, song0_.[Deleted] as column3_63_, song0_.[FavoritedTimes] as column4_63_, song0_.[LengthSeconds] as column5_63_, song0_.[NicoId] as column6_63_, song0_.[PersonalDescriptionAuthor] as column7_63_, song0_.[PersonalDescriptionText] as column8_63_, song0_.[PVServices] as column9_63_, song0_.[RatingScore] as column10_63_, song0_.[SongType] as column11_63_, song0_.[Status] as column12_63_, song0_.[ThumbUrl] as column13_63_, song0_.[Version] as column14_63_, song0_.[OriginalVersion] as column15_63_, song0_.[ReleaseEvent] as column16_63_, song0_.[AdditionalNamesString] as column17_63_, song0_.DefaultNameLanguage as defaultnamelanguage18_63_, song0_.JapaneseName as japanesename19_63_, song0_.EnglishName as englishname20_63_, song0_.RomajiName as romajiname21_63_, song0_.Notes as notes22_63_, song0_.NotesEng as noteseng23_63_, song0_.PublishDate as publishdate24_63_, song0_.ArtistString as artiststring25_63_, song0_.ArtistStringRomaji as artiststringromaji26_63_, song0_.ArtistStringEnglish as artiststringenglish27_63_, song0_.ArtistStringDefault as artiststringdefault28_63_ from dbo.Songs song0_ where  not (song0_.[Deleted]=1) and (1=0 or exists (select usages1_.Id from dbo.SongTagUsages usages1_ where song0_.Id=usages1_.[Song] and (usages1_.[Tag] in (@p0)))) order by (select cast(sum(usages2_.[Count]) as INT) from dbo.SongTagUsages usages2_ where song0_.Id=usages2_.[Song] and usages2_.[Tag]=@p1) desc OFFSET 0 ROWS FETCH FIRST @p2 ROWS ONLY ]
  
Name:p3 - Value:481  Name:p4 - Value:12  Name:p2 - Value:481

[SQL: select song0_.Id as id1_63_, song0_.[CreateDate] as column2_63_, song0_.[Deleted] as column3_63_, song0_.[FavoritedTimes] as column4_63_, song0_.[LengthSeconds] as column5_63_, song0_.[NicoId] as column6_63_, song0_.[PersonalDescriptionAuthor] as column7_63_, song0_.[PersonalDescriptionText] as column8_63_, song0_.[PVServices] as column9_63_, song0_.[RatingScore] as column10_63_, song0_.[SongType] as column11_63_, song0_.[Status] as column12_63_, song0_.[ThumbUrl] as column13_63_, song0_.[Version] as column14_63_, song0_.[OriginalVersion] as column15_63_, song0_.[ReleaseEvent] as column16_63_, song0_.[AdditionalNamesString] as column17_63_, song0_.DefaultNameLanguage as defaultnamelanguage18_63_, song0_.JapaneseName as japanesename19_63_, song0_.EnglishName as englishname20_63_, song0_.RomajiName as romajiname21_63_, song0_.Notes as notes22_63_, song0_.NotesEng as noteseng23_63_, song0_.PublishDate as publishdate24_63_, song0_.ArtistString as artiststring25_63_, song0_.ArtistStringRomaji as artiststringromaji26_63_, song0_.ArtistStringEnglish as artiststringenglish27_63_, song0_.ArtistStringDefault as artiststringdefault28_63_ from dbo.Songs song0_ where  not (song0_.[Deleted]=1) and (1=0 or exists (select usages1_.Id from dbo.SongTagUsages usages1_ where song0_.Id=usages1_.[Song] and (usages1_.[Tag] in (@p0)))) order by (select cast(sum(usages2_.[Count]) as INT) from dbo.SongTagUsages usages2_ where song0_.Id=usages2_.[Song] and usages2_.[Tag]=@p1) desc OFFSET 0 ROWS FETCH FIRST @p2 ROWS ONLY] System.Collections.IList DoList(NHibernate.Engine.ISessionImplementor, NHibernate.Engine.QueryParameters, NHibernate.Transform.IResultTransformer)    at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at VocaDb.Model.Database.Queries.TagQueries.GetTopUsagesAndCount[TUsage,TEntry,TSort,TSubType](IDatabaseContext`1 ctx, Int32 tagId, EntryType entryType, Func`3 whereExpression, Int32 maxCount) in C:\Sites\VocaDB\web\VocaDbModel\Database\Queries\TagQueries.cs:line 98
   at VocaDb.Model.Database.Queries.TagQueries.<>c__DisplayClass29_0.<GetDetails>b__0(IDatabaseContext`1 ctx) in C:\Sites\VocaDB\web\VocaDbModel\Database\Queries\TagQueries.cs:line 371
   at VocaDb.Model.Database.Repositories.NHibernate.NHibernateRepository`1.HandleQuery[TResult](Func`2 func, String failMsg) in C:\Sites\VocaDB\web\VocaDbModel\Database\Repositories\NHibernate\NHibernateRepository.cs:line 142
SqlException Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])
Win32Exception The wait operation timed out
```

Sometimes SQL server just uses a bad query plan. Perhaps just updating index statistics would help, but if not, add another index or tune the query.

This query should really be made async. It could even be another REST call.

**Comment by riipah** [comment]
For now I just made tag stats cached and added try-catch so that no stats are returned if there's an error.
