### ISSUE TITLE
Song submit not working

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#596]
**Website**
VocaDB

**Describe the bug**
Song submit page is not working. Stuck on loading after submitting the entry and returns "Unhandled Expcetion". 

Doesn't save info to the entries properly: https://vocadb.net/S/284681

- Title is visible but it doesn't shows up in the edit page (can't modify the entry)
- Revisions page is empty

**Comment by riipah** [comment]
Is this for ALL songs?

**Comment by AgFlore** [comment]
I was trying to add an https://vocadb.net/S/284679 and was also faced with the problem.

**Comment by riipah** [comment]
Are you sure it's not just a temporary timeout? I was able to create the song here https://vocadb.net/S/284693

**Comment by AgFlore** [comment]
> Are you sure it's not just a temporary timeout? I was able to create the song here https://vocadb.net/S/284693 . It can also fail because of timeout from Bilibili. 
I would say no because I also tried to add it without the PV embeded, still returning an error.
> I haven't checked the logs thoroughly yet.

**Comment by riipah** [comment]
Well then it was probably the system timeout because of backups/restart.

**Comment by riipah** [comment]
```
2020-06-12 12:59:08.9181 [] INFO Sending notifications for 2 artists 
2020-06-12 12:59:38.9206 [] ERROR Unexpected database error - NHibernate.Exceptions.GenericADOException could not execute query
[ select artistforu0_.[User] as col_0_0_, artistforu0_.[Artist] as col_1_0_ from dbo.ArtistsForUsers artistforu0_ inner join dbo.Users user1_ on artistforu0_.[User]=user1_.Id inner join dbo.UserOptions useroption2_ on user1_.Id=useroption2_.[User] where (artistforu0_.[Artist] in (@p0 , @p1)) and (artistforu0_.[User]<>@p2 or artistforu0_.[User] is null) and user1_.[Active]=1 and artistforu0_.[SiteNotifications]=1 and (select cast(count(*) as INT) from dbo.UserMessages receivedme3_ where user1_.Id=receivedme3_.[Receiver] and receivedme3_.[Inbox]=@p3 and  not (receivedme3_.[Read]=1))<useroption2_.[UnreadNotificationsToKeep] ]
  Name:p2 - Value:12186  Name:p3 - Value:3  Name:p1_0_ - Value:10025  Name:p1_1_ - Value:7400
[SQL: select artistforu0_.[User] as col_0_0_, artistforu0_.[Artist] as col_1_0_ from dbo.ArtistsForUsers artistforu0_ inner join dbo.Users user1_ on artistforu0_.[User]=user1_.Id inner join dbo.UserOptions useroption2_ on user1_.Id=useroption2_.[User] where (artistforu0_.[Artist] in (@p0 , @p1)) and (artistforu0_.[User]<>@p2 or artistforu0_.[User] is null) and user1_.[Active]=1 and artistforu0_.[SiteNotifications]=1 and (select cast(count(*) as INT) from dbo.UserMessages receivedme3_ where user1_.Id=receivedme3_.[Receiver] and receivedme3_.[Inbox]=@p3 and  not (receivedme3_.[Read]=1))<useroption2_.[UnreadNotificationsToKeep]] System.Collections.IList DoList(NHibernate.Engine.ISessionImplementor, NHibernate.Engine.QueryParameters, NHibernate.Transform.IResultTransformer)    at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at VocaDb.Model.Service.Helpers.FollowedArtistNotifier.SendNotifications(IDatabaseContext ctx, IEntryWithNames entry, IEnumerable`1 artists, IUser creator) in C:\Sites\VocaDB\web\VocaDbModel\Service\Helpers\FollowedArtistNotifier.cs:line 96
   at VocaDb.Model.Database.Queries.SongQueries.<>c__DisplayClass58_0.<UpdateBasicProperties>b__1(IDatabaseContext`1 ctx) in C:\Sites\VocaDB\web\VocaDbModel\Database\Queries\SongQueries.cs:line 1191
   at VocaDb.Model.Database.Repositories.NHibernate.NHibernateRepository`1.HandleTransaction[TResult](Func`2 func, String failMsg) in C:\Sites\VocaDB\web\VocaDbModel\Database\Repositories\NHibernate\NHibernateRepository.cs:line 174
SqlException Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])
Win32Exception The wait operation timed out
```

There is some timeout when sending notification messages. Probably there's too many users following an artist. A database index needs to be added.

**Comment by Shiroizu** [comment]
Tried adding https://www.nicovideo.jp/watch/sm37014769, unhandled error.

Same with youtube: https://www.youtube.com/watch?v=tjyDo0c0pjg

**Comment by riipah** [comment]
I was able to add the YouTube song just fine. Weird.

**Comment by Shiroizu** [comment]
Another one, tried with different browsers as well: https://www.youtube.com/watch?v=l4Z-k3nfgbY

**Comment by riipah** [comment]
I was able to add it if I remove Kasane Teto from the list.

I think I know what's happening. After restart, SQL Server has picked a poor query plan for followed artists and it's now using the cached query plan. It happens sometimes.

**Comment by Shiroizu** [comment]
Thanks, that approach seems to work.

**Comment by Shiroizu** [comment]
I think the issue happens when trying to submit a song with two artists. Adding a song with only one artist works fine, no matter the follower count.

**Comment by Shiroizu** [comment]
Entry updating works only if one artist is added at a time (not including custom artists)

**Comment by Shiroizu** [comment]
Adding two new media links also doesn't work. Adding multiple external links does work though.

**Comment by riipah** [comment]
Well can't figure out any indexes to add, and the query doesn't seem too slow right now (SQL server flushes the cache at some point). I made it so that a possible database error during notifications won't crash the save though, and tried to simplify the query. The notifier has to check number of *unread* messages each user has. And for artists with many followers that can be a lot of data... though the existing indexes should be enough, but sometimes the server just ignores them if the query plan is suboptimal.

**Comment by riipah** [comment]
Well it seems from the logs that this is still happening. For some reason it started happening after the system restart. Unfortunately I have no more time to spend on this.
