### ISSUE TITLE
MikuBot (WCF) call fails

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#696]
**Website**
VocaDB

**Describe the bug**
MikuBut is calling VocaDB, but VocaDB is throwing exception

**To Reproduce**
1. Post a message in IRC

**Additional context**

Stack trace:
```
---> (Inner Exception #0) System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Object reference not set to an instance of an object. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.NullReferenceException: Object reference not set to an instance of an object.
   at VocaDb.Web.AspNetHttpContext.get_User() in C:\Sites\VocaDB\web\VocaDbWeb\Code\Web\AspNetHttpContext.cs:line 23
   at VocaDb.Model.Service.Security.LoginManager.get_IsLoggedIn() in C:\Sites\VocaDB\web\VocaDbModel\Service\Security\LoginManager.cs:line 92
   at VocaDb.Model.Service.Security.LoginManager.get_LoggedUser() in C:\Sites\VocaDB\web\VocaDbModel\Service\Security\LoginManager.cs:line 113
   at VocaDb.Model.Service.Security.LoginManager.get_UserGroupId() in C:\Sites\VocaDB\web\VocaDbModel\Service\Security\LoginManager.cs:line 128
   at VocaDb.Model.Domain.Security.EntryPermissionManager.CanEditPersonalDescription(IUserPermissionContext userContext, IEntryBase entry) in C:\Sites\VocaDB\web\VocaDbModel\Domain\Security\EntryPermissionManager.cs:line 212
```

MikuBot calls VocaDB using the WCF service QueryService.svc. During WCF call, HttpContext is null. MikuBot shouldn't need any HttpContext (or user), so it's okay.

**Comment by ycanardeau** [comment]
I added some null checks. The exception has disappeared, but MikuBot still doesn't work correctly for some reason.
